/**
 * `analyze` command — Multi-agent product idea analysis.
 *
 * Takes a product idea and runs it simultaneously through market, tech,
 * and product agents, producing a comprehensive analysis report.
 *
 * @module commands/analyze
 */

import ora from 'ora';
import chalk from 'chalk';
import inquirer from 'inquirer';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { loadConfig } from '../utils/config.js';
import { analyzeMarket } from '../agents/market.js';
import { analyzeTech } from '../agents/tech.js';
import { analyzeProduct } from '../agents/product.js';

/**
 * Demo output shown when `--demo` flag is used.
 * @type {string}
 */
const DEMO_OUTPUT = `# OnePersonAI — Multi-Agent Analysis Report (DEMO)

**Generated:** 2025-01-15 10:30:00
**Agents run:** 3

---

## ✅ Market Agent (1420ms)

### 1. Total Addressable Market (TAM)
- **Market Size:** $4.2B by 2027 (CAGR 28%)
- **Key Segments:** Independent developers (62%), small studios (23%), enterprises (15%)

### 2. Competitive Landscape
| Competitor | Strength | Weakness |
|---|---|---|
| Tool A | Brand recognition | Expensive, enterprise-focused |
| Tool B | Free tier | Limited AI features |
| Tool C | Good UX | Closed ecosystem |

### 3. Differentiation
First AI toolkit purpose-built for solo builders — combining analysis, scaffolding, and review in one CLI.

---

## ✅ Tech Agent (1890ms)

### Recommended Stack
- **Runtime:** Node.js 22 (ESM, fast startup)
- **CLI Framework:** Commander.js + Chalk + Ora
- **AI Integration:** AO binary at /usr/bin/ao
- **Format:** Markdown reports

### Architecture
Single-entry CLI with subcommands → Agent modules → AO subprocess → Formatted output

---

## ✅ Product Agent (1340ms)

### MVP Scope (2 weeks)
1. CLI with 3 commands (analyze, scaffold, review)
2. 3 analysis agents (market, tech, product)
3. Content generation for docs
4. Basic scaffolding from templates

### Roadmap
- **Week 1:** Core CLI + analyze command
- **Week 2:** Scaffold + review commands
- **Week 3:** Content generation + polish
- **Week 4:** Documentation, examples, ship

---

_Generated by OnePersonAI (Demo Mode)_`;

/**
 * Prompt the user for a product idea if not provided.
 *
 * @returns {Promise<string>} The product idea text
 */
async function promptForIdea() {
  const { idea } = await inquirer.prompt([
    {
      type: 'input',
      name: 'idea',
      message: 'Describe your product idea:',
      validate: (input) => (input.trim().length > 0 ? true : 'Please enter a product idea'),
    },
  ]);
  return idea.trim();
}

/**
 * Run the analyze command.
 *
 * @param {string} idea - Product idea (empty string to prompt)
 * @param {object} options - Command options
 * @param {boolean} [options.demo] - Show demo output without running agents
 * @param {string} [options.model] - AI model override
 * @param {boolean} [options.quiet] - Suppress spinners
 * @param {string} [options.out] - Output file path
 * @returns {Promise<void>}
 */
export default async function analyzeCommand(idea, options = {}) {
  // Handle demo mode
  if (options.demo) {
    console.log(chalk.cyan.bold('\n🧪 Demo Mode — Showing example output\n'));
    console.log(DEMO_OUTPUT);

    if (options.out) {
      const outPath = resolve(process.cwd(), options.out);
      const outDir = outPath.substring(0, outPath.lastIndexOf('/'));
      if (!existsSync(outDir)) {
        mkdirSync(outDir, { recursive: true });
      }
      writeFileSync(outPath, DEMO_OUTPUT, 'utf-8');
      console.log(chalk.green(`\n✓ Report saved to ${outPath}`));
    }

    console.log(chalk.dim('\nRun without --demo for real AI-powered analysis.'));
    return;
  }

  // Get the idea
  const productIdea = idea || await promptForIdea();
  console.log(chalk.bold.cyan('\n🔍 OnePersonAI — Multi-Agent Analysis\n'));

  const config = loadConfig();
  const model = options.model || config.model;

  // Show what we're doing
  console.log(chalk.dim(`Model: ${model}`));
  console.log(chalk.dim(`Idea: ${productIdea.substring(0, 80)}${productIdea.length > 80 ? '...' : ''}`));
  console.log('');

  // Run all three agents concurrently with spinners
  const marketSpinner = ora({ text: 'Market Analysis Agent', color: 'yellow' }).start();
  const techSpinner = ora({ text: 'Tech Stack Agent', color: 'blue' }).start();
  const productSpinner = ora({ text: 'Product Strategy Agent', color: 'magenta' }).start();

  const hideSpinners = () => [marketSpinner, techSpinner, productSpinner].forEach(s => s.stop());

  try {
    const [marketResult, techResult, productResult] = await Promise.all([
      analyzeMarket(productIdea, { model }).then(r => {
        if (r.usedFallback) marketSpinner.warn(chalk.yellow('Market (fallback)'));
        else marketSpinner.succeed(chalk.green('Market'));
        return r;
      }).catch(e => {
        marketSpinner.fail(chalk.red('Market'));
        return { success: false, raw: '', error: e.message, usedFallback: false };
      }),
      analyzeTech(productIdea, { model }).then(r => {
        if (r.usedFallback) techSpinner.warn(chalk.yellow('Tech (fallback)'));
        else techSpinner.succeed(chalk.green('Tech'));
        return r;
      }).catch(e => {
        techSpinner.fail(chalk.red('Tech'));
        return { success: false, raw: '', error: e.message, usedFallback: false };
      }),
      analyzeProduct(productIdea, { model }).then(r => {
        if (r.usedFallback) productSpinner.warn(chalk.yellow('Product (fallback)'));
        else productSpinner.succeed(chalk.green('Product'));
        return r;
      }).catch(e => {
        productSpinner.fail(chalk.red('Product'));
        return { success: false, raw: '', error: e.message, usedFallback: false };
      }),
    ]);

    console.log('');

    // Build the combined report
    const reportParts = [
      '# OnePersonAI — Multi-Agent Analysis Report',
      '',
      `**Idea:** ${productIdea}`,
      `**Model:** ${model}`,
      `**Generated:** ${new Date().toISOString().replace(/T/, ' ').replace(/\.\d+Z/, '')}`,
      '',
    ];

    const results = [
      { name: 'Market Analysis', result: marketResult },
      { name: 'Tech Stack Analysis', result: techResult },
      { name: 'Product Strategy', result: productResult },
    ];

    for (const { name, result } of results) {
      reportParts.push('---', `## ${name}`, '');
      if (result.success) {
        reportParts.push(result.raw || '_No output_');
      } else {
        reportParts.push(`> ⚠  Agent failed: ${result.error || 'Unknown error'}`);
      }
      reportParts.push('');
    }

    reportParts.push('---', '_Generated by OnePersonAI_');

    const fullReport = reportParts.join('\n');

    // Output to file if requested
    if (options.out) {
      const outPath = resolve(process.cwd(), options.out);
      const outDir = outPath.substring(0, outPath.lastIndexOf('/'));
      if (!existsSync(outDir)) {
        mkdirSync(outDir, { recursive: true });
      }
      writeFileSync(outPath, fullReport, 'utf-8');
      console.log(chalk.green(`✓ Report saved to ${outPath}\n`));
    }

    // Print to stdout
    if (!options.quiet) {
      console.log(chalk.cyan.bold('═══ ANALYSIS REPORT ═══\n'));
      console.log(fullReport);
      console.log(chalk.cyan.bold('\n═══════════════════════\n'));
    }

    // Summary
    const succeeded = results.filter(r => r.result.success).length;
    const total = results.length;
    console.log(chalk.bold(`\nResults: ${chalk.green(`${succeeded}/${total} agents succeeded`)}`));

    if (results.some(r => r.result.usedFallback)) {
      console.log(chalk.yellow('\n⚠  Some agents used local fallback (AO not available).'));
      console.log(chalk.yellow('   Install the AO orchestrator for AI-powered analysis.'));
    }

  } catch (err) {
    hideSpinners();
    console.error(chalk.red('\n✗ Analysis failed:'), err.message);
    process.exitCode = 1;
  }
}
