/**
 * `scaffold` command — Project structure generator.
 *
 * Takes a project plan (from analyze output or manually specified) and
 * generates a complete project structure: directories, package.json,
 * and basic source files.
 *
 * @module commands/scaffold
 */

import ora from 'ora';
import chalk from 'chalk';
import inquirer from 'inquirer';
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, join, dirname } from 'node:path';

/**
 * Default files to create for any new project.
 * @type {Array<{path: string, content: string}>}
 */
const DEFAULT_FILES = [
  {
    path: '.gitignore',
    content: `node_modules/
dist/
.env
*.log
.DS_Store
`,
  },
  {
    path: '.env.example',
    content: `# OnePersonAI generated project
# Copy to .env and fill in your values
PORT=3000
NODE_ENV=development
`,
  },
  {
    path: 'src/index.js',
    content: `/**
 * Entry point — placeholder generated by OnePersonAI scaffold.
 */
import { createServer } from 'node:http';

const PORT = process.env.PORT || 3000;

const server = createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ status: 'ok', message: 'Hello from OnePersonAI!' }));
});

server.listen(PORT, () => {
  console.log(\`Server running on http://localhost:\${PORT}\`);
});
`,
  },
];

/**
 * Package.json template factory.
 *
 * @param {string} name - Project name
 * @param {string} description - Project description
 * @returns {object} Package.json contents
 */
function makePackageJson(name, description) {
  return {
    name: name.toLowerCase().replace(/[^a-z0-9-]/g, '-'),
    version: '1.0.0',
    description: description || 'Project generated by OnePersonAI',
    main: 'src/index.js',
    type: 'module',
    scripts: {
      start: 'node src/index.js',
      dev: 'node --watch src/index.js',
    },
    keywords: [],
    license: 'MIT',
  };
}

/**
 * Scaffold types and their directory structure.
 * @type {Object<string, {dirs: string[], files: Array<{path: string, content: string}>}>}
 */
const SCAFFOLD_TEMPLATES = {
  'cli-tool': {
    dirs: ['bin', 'src/commands', 'src/utils', 'src/agents', 'src/orchestrator', 'tests'],
    files: [
      {
        path: 'bin/cli.js',
        content: `#!/usr/bin/env node\n\nimport('../src/index.js').catch(console.error);\n`,
      },
    ],
  },
  'web-app': {
    dirs: ['src/routes', 'src/middleware', 'src/models', 'public', 'views'],
    files: [],
  },
  'api-service': {
    dirs: ['src/routes', 'src/middleware', 'src/models', 'src/services', 'tests'],
    files: [
      {
        path: 'src/services/README.md',
        content: '# Services\n\nBusiness logic layer for the API service.\n',
      },
    ],
  },
  'library': {
    dirs: ['src', 'tests', 'examples'],
    files: [],
  },
};

/**
 * Resolve page number fallback for inquirer.
 * @returns {Promise<{name: string, description: string, template: string}>}
 */
async function promptForProject() {
  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'name',
      message: 'Project name:',
      default: 'my-solo-project',
      validate: (v) => (v.trim() ? true : 'Project name is required'),
    },
    {
      type: 'input',
      name: 'description',
      message: 'Short description:',
      default: '',
    },
    {
      type: 'list',
      name: 'template',
      message: 'Project type:',
      choices: [
        { name: 'CLI Tool', value: 'cli-tool' },
        { name: 'Web Application', value: 'web-app' },
        { name: 'API Service', value: 'api-service' },
        { name: 'Library / Package', value: 'library' },
        { name: 'Custom (minimal)', value: 'custom' },
      ],
    },
  ]);
  return answers;
}

/**
 * Run the scaffold command.
 *
 * @param {string} projectDir - Target directory (default: current dir)
 * @param {object} options - Command options
 * @param {string} [options.name] - Project name
 * @param {string} [options.description] - Project description
 * @param {string} [options.template] - Scaffold template name
 * @param {boolean} [options.force] - Overwrite existing files
 * @returns {Promise<void>}
 */
export default async function scaffoldCommand(projectDir = '.', options = {}) {
  const targetDir = resolve(process.cwd(), projectDir);

  console.log(chalk.bold.cyan('\n🏗️  OnePersonAI — Project Scaffold\n'));

  // Prompt interactively if not enough info provided
  const answers = await promptForProject();

  const projectName = options.name || answers.name;
  const description = options.description || answers.description;
  const templateKey = options.template || answers.template;

  // Check if target directory exists and is non-empty
  if (existsSync(targetDir)) {
    try {
      const { readdirSync } = await import('node:fs');
      const contents = readdirSync(targetDir);
      if (contents.length > 0 && !options.force) {
        const { overwrite } = await inquirer.prompt([
          {
            type: 'confirm',
            name: 'overwrite',
            message: `Directory ${targetDir} is not empty. Continue?`,
            default: false,
          },
        ]);
        if (!overwrite) {
          console.log(chalk.yellow('Scaffold cancelled.'));
          return;
        }
      }
    } catch {
      // If we can't read it, proceed
    }
  }

  const spinner = ora({ text: 'Generating project structure...', color: 'green' }).start();

  try {
    // Determine directories and template files
    const template = SCAFFOLD_TEMPLATES[templateKey] || { dirs: [], files: [] };
    const allDirs = [...template.dirs, ''].filter(Boolean); // ensure root exists

    // Create all directories
    for (const dir of allDirs) {
      mkdirSync(join(targetDir, dir), { recursive: true });
    }

    // Create package.json
    const pkg = makePackageJson(projectName, description);
    writeFileSync(
      join(targetDir, 'package.json'),
      JSON.stringify(pkg, null, 2) + '\n',
      'utf-8',
    );
    spinner.text = 'Created package.json ✓';

    // Write default files
    for (const file of DEFAULT_FILES) {
      const filePath = join(targetDir, file.path);
      const fileDir = dirname(filePath);
      if (!existsSync(fileDir)) mkdirSync(fileDir, { recursive: true });
      writeFileSync(filePath, file.content, 'utf-8');
    }
    spinner.text = 'Created config files ✓';

    // Write template-specific files
    for (const file of template.files) {
      const filePath = join(targetDir, file.path);
      const fileDir = dirname(filePath);
      if (!existsSync(fileDir)) mkdirSync(fileDir, { recursive: true });
      writeFileSync(filePath, file.content, 'utf-8');
    }
    spinner.text = 'Created template files ✓';

    // Create a basic README.md if none exists
    const readmePath = join(targetDir, 'README.md');
    if (!existsSync(readmePath)) {
      const readmeContent = [
        `# ${projectName}`,
        '',
        description || 'Generated by OnePersonAI',
        '',
        '## Quick Start',
        '',
        '```bash',
        'npm install',
        'npm start',
        '```',
        '',
      ].join('\n');
      writeFileSync(readmePath, readmeContent, 'utf-8');
    }

    spinner.succeed(chalk.green('Project scaffolded successfully!'));

    // Summary
    console.log('');
    console.log(chalk.bold('📁 Project structure:'));
    console.log(chalk.dim(`  ${targetDir}/`));
    for (const dir of allDirs) {
      console.log(chalk.dim(`  ├── ${dir}/`));
    }
    console.log(chalk.dim('  ├── package.json'));
    console.log(chalk.dim('  ├── .gitignore'));
    console.log(chalk.dim('  ├── .env.example'));
    console.log(chalk.dim('  └── README.md'));
    console.log('');
    console.log(chalk.green('Next steps:'));
    console.log(chalk.cyan(`  cd ${projectDir === '.' ? '.' : projectDir}`));
    console.log(chalk.cyan('  npm install'));
    console.log(chalk.cyan('  npm start'));
    console.log('');

  } catch (err) {
    spinner.fail(chalk.red('Scaffold failed'));
    console.error(chalk.red(`\n✗ Error: ${err.message}`));
    process.exitCode = 1;
  }
}
