/**
 * Content Generation Agent.
 *
 * Generates README docs, elevator pitches, landing page copy, feature
 * bullet points, and social media posts for a product idea.
 * Runs through AO binary or uses local fallback.
 *
 * @module agents/content
 */

import { loadConfig, isAoAvailable } from '../utils/config.js';
import { contentPrompt } from '../utils/prompts.js';
import { runAoAgent } from '../orchestrator/index.js';

/**
 * Result of content generation.
 * @typedef {Object} ContentResult
 * @property {boolean} success - Whether generation completed
 * @property {string} raw - Raw text output
 * @property {string} [error] - Error message if failed
 * @property {boolean} [usedFallback] - Whether local fallback was used
 */

/**
 * Generate content for a product idea.
 *
 * @param {string} idea - The product idea
 * @param {object} [options] - Optional settings
 * @param {string} [options.model] - AI model to use (overrides config)
 * @param {object} [options.context] - Additional context (tech stack, audience, etc.)
 * @returns {Promise<ContentResult>} Generated content
 */
export async function generateContent(idea, options = {}) {
  const config = loadConfig();
  const prompt = contentPrompt(idea, options.context || {});

  if (isAoAvailable()) {
    try {
      const raw = await runAoAgent(prompt, {
        model: options.model || config.model,
        agentName: 'content',
      });
      return { success: true, raw, usedFallback: false };
    } catch (err) {
      return fallbackContent(idea, err.message);
    }
  }

  return fallbackContent(idea, 'AO binary not found at ' + config.aoPath);
}

/**
 * Local fallback content generation when AO is not available.
 *
 * @param {string} idea - The product idea
 * @param {string} [reason] - Why fallback was triggered
 * @returns {ContentResult}
 */
function fallbackContent(idea, reason = '') {
  const name = idea.trim().split(/\n/)[0] || 'YourProduct';
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'your-product';

  const lines = [
    '# Generated Content (Local — AO not available)',
    '',
    `**Product:** ${name}`,
    '',
    '> ⚠  This is template-based content. Install AO for AI-generated copy.',
    reason ? `> _Reason: ${reason}_` : '',
    '',
    '---',
    '',
    '## 1. README.md',
    '',
    `# ${name}`,
    '',
    '> AI-powered tool for solo builders — built by one person, for everyone.',
    '',
    '### Quick Start',
    '',
    '```bash',
    'npm install',
    'npm start',
    '```',
    '',
    '### Features',
    '',
    '- Describe your core feature here.',
    '- Explain what makes it unique.',
    '- Keep it concise for the README.',
    '',
    '### Tech Stack',
    '',
    '- Node.js / TypeScript',
    '- Modern frontend framework',
    '- PostgreSQL or equivalent',
    '',
    '---',
    '',
    '## 2. Elevator Pitch',
    '',
    `${name} helps [target audience] achieve [outcome] via [core mechanism].` +
    ` Unlike [competitors], we [key differentiator]. Built for solo builders seeking maximum impact.`,
    '',
    '---',
    '',
    '## 3. Landing Page Headlines',
    '',
    '1. **Build Solo. Ship Fast.** — ' +
      `${name} gives solo builders the toolkit to go from idea to launch in days, not months.`,
    '2. **Your AI Co-Founder.** — ${name} analyzes, plans, and generates content so you can focus on building.',
    '3. **From Idea to Product — One Person, One Tool.** — ' +
      'The first AI toolkit designed specifically for solo builders.',
    '',
    '---',
    '',
    '## 4. Feature Highlights',
    '',
    '- 🧠 **Multi-Agent Analysis** — Market, tech, and product agents analyze your idea from every angle.',
    '- 🏗️ **Instant Scaffolding** — Generate project structure, configs, and boilerplate in seconds.',
    '- 📝 **Content Generation** — README, docs, landing page copy, and social posts — all AI-driven.',
    '- 🔍 **Code Review** — Catch quality, security, and structural issues before they ship.',
    '- 🚀 **Solo-First Design** — Built for one-person teams with no fluff or enterprise overhead.',
    '',
    '---',
    '',
    '## 5. Social Media Launch Post',
    '',
    `Built ${name} solo. Here's what I learned:\n\n` +
    '1. AI agents for analysis save days of research\n' +
    '2. Scaffolding from specs keeps you moving\n' +
    "3. Solo doesn't mean alone — use tools that amplify\n\n" +
    'Check it out 👇',
    '',
    '---',
    '_Generated by OnePersonAI Content Agent (Fallback Mode)_',
  ];

  return {
    success: true,
    raw: lines.filter(Boolean).join('\n'),
    usedFallback: true,
  };
}
