/**
 * Market Analysis Agent.
 *
 * Analyzes total addressable market, competitors, differentiation, and
 * go-to-market strategy for a given product idea.  Runs the market prompt
 * through the AO binary or falls back to a local analysis template.
 *
 * @module agents/market
 */

import { loadConfig, isAoAvailable } from '../utils/config.js';
import { marketPrompt } from '../utils/prompts.js';
import { runAoAgent } from '../orchestrator/index.js';

/**
 * Result of a market analysis.
 * @typedef {Object} MarketAnalysisResult
 * @property {boolean} success - Whether the analysis completed
 * @property {string} raw - Raw text output from the analysis
 * @property {string} [error] - Error message if failed
 * @property {boolean} [usedFallback] - Whether local fallback was used
 */

/**
 * Run a market analysis on a product idea.
 *
 * @param {string} idea - The product idea to analyze
 * @param {object} [options] - Optional settings
 * @param {string} [options.model] - AI model to use (overrides config)
 * @returns {Promise<MarketAnalysisResult>} Analysis result
 */
export async function analyzeMarket(idea, options = {}) {
  const config = loadConfig();
  const prompt = marketPrompt(idea);

  if (isAoAvailable()) {
    try {
      const raw = await runAoAgent(prompt, {
        model: options.model || config.model,
        agentName: 'market',
      });
      return { success: true, raw, usedFallback: false };
    } catch (err) {
      // Fall through to local fallback
      return fallbackMarketAnalysis(idea, err.message);
    }
  }

  return fallbackMarketAnalysis(idea, 'AO binary not found at ' + config.aoPath);
}

/**
 * Local fallback market analysis when AO is not available.
 * Provides a template-based analysis using built-in logic.
 *
 * @param {string} idea - The product idea
 * @param {string} [reason] - Why fallback was triggered
 * @returns {MarketAnalysisResult}
 */
function fallbackMarketAnalysis(idea, reason = '') {
  const lines = [
    '# Market Analysis (Local — AO not available)',
    '',
    `**Idea:** ${idea}`,
    '',
    '> ⚠  This is a template-based analysis. Install AO for AI-powered analysis.',
    reason ? `> _Reason: ${reason}_` : '',
    '',
    '## 1. Total Addressable Market (TAM)',
    '',
    '- **Estimate:** Unable to compute without AI model.',
    '- **Tip:** Define your niche clearly — solo builders succeed in focused markets.',
    '- **Research:** Use tools like Gartner, Statista, or CB Insights for your sector.',
    '',
    '## 2. Target Audience',
    '',
    '- **Primary:** End users directly benefiting from the product.',
    '- **Secondary:** Partners, integrators, or enterprise buyers.',
    '- **Action:** Interview 5-10 potential users before building.',
    '',
    '## 3. Competitive Landscape',
    '',
    '- **Direct competitors:** Identify 3 alternatives and what they charge.',
    '- **Indirect competitors:** Adjacent tools users might substitute.',
    '- **Your edge:** Speed, simplicity, AI-native, or solo-builder focus.',
    '',
    '## 4. Differentiation & Positioning',
    '',
    '- **Unique value:** What can you do that incumbents cannot?',
    '- **Positioning:** "The [category] for [audience] that [benefit]."',
    '',
    '## 5. Market Risks',
    '',
    '- **Adoption barrier:** Users must change existing workflows.',
    '- **Timing:** Is the market ready?',
    '- **Competition:** Well-funded incumbents may copy features.',
    '',
    '## 6. Go-to-Market Strategy',
    '',
    '- **Channel:** Product Hunt, Hacker News, social media, community.',
    '- **Pricing:** Consider freemium or usage-based for solo builders.',
    '- **Launch:** Start with a focused community (Reddit, Discord, Twitter).',
    '',
    '---',
    '_Generated by OnePersonAI Market Agent (Fallback Mode)_',
  ];

  return {
    success: true,
    raw: lines.filter(Boolean).join('\n'),
    usedFallback: true,
  };
}
