/**
 * Product Strategy Agent.
 *
 * Defines MVP scope, feature roadmap, user experience priorities, success
 * metrics, and monetization strategy for a product idea.
 * Runs through AO binary or uses local fallback.
 *
 * @module agents/product
 */

import { loadConfig, isAoAvailable } from '../utils/config.js';
import { productPrompt } from '../utils/prompts.js';
import { runAoAgent } from '../orchestrator/index.js';

/**
 * Result of a product analysis.
 * @typedef {Object} ProductAnalysisResult
 * @property {boolean} success - Whether the analysis completed
 * @property {string} raw - Raw text output from the analysis
 * @property {string} [error] - Error message if failed
 * @property {boolean} [usedFallback] - Whether local fallback was used
 */

/**
 * Run a product strategy analysis on a product idea.
 *
 * @param {string} idea - The product idea to analyze
 * @param {object} [options] - Optional settings
 * @param {string} [options.model] - AI model to use (overrides config)
 * @returns {Promise<ProductAnalysisResult>} Analysis result
 */
export async function analyzeProduct(idea, options = {}) {
  const config = loadConfig();
  const prompt = productPrompt(idea);

  if (isAoAvailable()) {
    try {
      const raw = await runAoAgent(prompt, {
        model: options.model || config.model,
        agentName: 'product',
      });
      return { success: true, raw, usedFallback: false };
    } catch (err) {
      return fallbackProductAnalysis(idea, err.message);
    }
  }

  return fallbackProductAnalysis(idea, 'AO binary not found at ' + config.aoPath);
}

/**
 * Local fallback product analysis when AO is not available.
 *
 * @param {string} idea - The product idea
 * @param {string} [reason] - Why fallback was triggered
 * @returns {ProductAnalysisResult}
 */
function fallbackProductAnalysis(idea, reason = '') {
  const lines = [
    '# Product Strategy Analysis (Local — AO not available)',
    '',
    `**Idea:** ${idea}`,
    '',
    '> ⚠  This is a template-based analysis. Install AO for AI-powered analysis.',
    reason ? `> _Reason: ${reason}_` : '',
    '',
    '## 1. MVP Scope',
    '',
    '- **Core loop:** Identify the single action users take that delivers value.',
    '- **MVP features:** The smallest set of features to enable that core loop.',
    '- **Stretch:** Remove everything that isn\'t essential. You can always add later.',
    '',
    '## 2. Feature Roadmap',
    '',
    '### MVP (Weeks 1-4)',
    '- Core functionality end-to-end.',
    '- Basic auth and onboarding.',
    '- Simple UI — prioritize function over form.',
    '',
    '### v1 (Weeks 5-10)',
    '- Polish UI/UX.',
    '- Add 2-3 high-impact features based on user feedback.',
    '- Basic analytics and monitoring.',
    '',
    '### v2 (Weeks 11+)',
    '- Advanced features.',
    '- Performance optimization.',
    '- Monetization features (billing, tiers).',
    '',
    '## 3. User Experience Priorities',
    '',
    '- **First-run experience:** Users should see value in under 60 seconds.',
    '- **Error handling:** Clear, helpful error messages — not stack traces.',
    '- **Mobile responsive:** Many solo builders preview on mobile.',
    '',
    '## 4. Success Metrics',
    '',
    '- **Activation:** % of signups that complete the core action.',
    '- **Retention:** DAU/MAU ratio, weekly active usage.',
    '- **Revenue:** MRR, conversion rate (if monetized).',
    '- **Feedback:** NPS or qualitative user interview cadence.',
    '',
    '## 5. Monetization Strategy',
    '',
    '- **Solo-friendly:** Freemium or low-cost starter tier.',
    '- **Value-based:** Price based on usage, seats, or features.',
    '- **Transparent:** Clear pricing page — no "contact us" gate.',
    '',
    '## 6. Key Risks & Mitigations',
    '',
    '- **Building the wrong thing:** Ship MVP fast, get feedback within 2 weeks.',
    '- **Burnout:** Scope ruthlessly. Solo builders need velocity, not perfection.',
    '- **No traction:** Have a clear "pivot or persevere" checkpoint at week 6.',
    '',
    '---',
    '_Generated by OnePersonAI Product Agent (Fallback Mode)_',
  ];

  return {
    success: true,
    raw: lines.filter(Boolean).join('\n'),
    usedFallback: true,
  };
}
