/**
 * Tech Stack Analysis Agent.
 *
 * Evaluates technical feasibility, recommends a tech stack, outlines
 * architecture, and estimates development complexity for a product idea.
 * Runs through AO binary or uses local fallback.
 *
 * @module agents/tech
 */

import { loadConfig, isAoAvailable } from '../utils/config.js';
import { techPrompt } from '../utils/prompts.js';
import { runAoAgent } from '../orchestrator/index.js';

/**
 * Result of a tech analysis.
 * @typedef {Object} TechAnalysisResult
 * @property {boolean} success - Whether the analysis completed
 * @property {string} raw - Raw text output from the analysis
 * @property {string} [error] - Error message if failed
 * @property {boolean} [usedFallback] - Whether local fallback was used
 */

/**
 * Run a tech stack analysis on a product idea.
 *
 * @param {string} idea - The product idea to analyze
 * @param {object} [options] - Optional settings
 * @param {string} [options.model] - AI model to use (overrides config)
 * @returns {Promise<TechAnalysisResult>} Analysis result
 */
export async function analyzeTech(idea, options = {}) {
  const config = loadConfig();
  const prompt = techPrompt(idea);

  if (isAoAvailable()) {
    try {
      const raw = await runAoAgent(prompt, {
        model: options.model || config.model,
        agentName: 'tech',
      });
      return { success: true, raw, usedFallback: false };
    } catch (err) {
      return fallbackTechAnalysis(idea, err.message);
    }
  }

  return fallbackTechAnalysis(idea, 'AO binary not found at ' + config.aoPath);
}

/**
 * Local fallback tech analysis when AO is not available.
 *
 * @param {string} idea - The product idea
 * @param {string} [reason] - Why fallback was triggered
 * @returns {TechAnalysisResult}
 */
function fallbackTechAnalysis(idea, reason = '') {
  const lines = [
    '# Tech Stack Analysis (Local — AO not available)',
    '',
    `**Idea:** ${idea}`,
    '',
    '> ⚠  This is a template-based analysis. Install AO for AI-powered analysis.',
    reason ? `> _Reason: ${reason}_` : '',
    '',
    '## 1. Technical Feasibility',
    '',
    '- **Verdict:** Assess based on your skills. Solo builders should leverage existing platforms.',
    '- **Key question:** What\'s the hardest technical problem, and do you have a path to solve it?',
    '',
    '## 2. Recommended Tech Stack',
    '',
    '- **Frontend:** Next.js (React) or SvelteKit — fast development, good DX.',
    '- **Backend:** Node.js with Express/Fastify or Python with FastAPI.',
    '- **Database:** PostgreSQL (relational) or SQLite (simple). Supabase for hosted.',
    '- **AI/ML:** OpenAI API, Anthropic Claude, or local models via Ollama.',
    '- **Deployment:** Vercel, Railway, or Fly.io — minimal DevOps overhead.',
    '',
    '## 3. Architecture Overview',
    '',
    '- **Pattern:** Monolith-first for MVP. Split into services only when needed.',
    '- **API:** REST or GraphQL. Consider WebSockets for real-time features.',
    '- **Auth:** Clerk, Auth0, or Supabase Auth for quick setup.',
    '',
    '## 4. Key Dependencies',
    '',
    '- Hosting platform with edge/global distribution.',
    '- Database provider or self-hosted option.',
    '- AI model API key (OpenAI, Anthropic, etc.).',
    '- Email service (Resend, SendGrid) if needed.',
    '',
    '## 5. Development Complexity',
    '',
    '- **MVP:** 4-8 weeks for a solo builder working evenings/weekends.',
    '- **v1:** 8-16 weeks with core features and polish.',
    '- **v2:** 16+ weeks with advanced features, scale, and optimization.',
    '',
    '## 6. Scalability Considerations',
    '',
    '- **Bottlenecks:** Database queries, AI API latency, file storage.',
    '- **Strategy:** Optimize later. Premature scaling kills solo projects.',
    '- **Budget:** Monitor API costs closely — they add up fast.',
    '',
    '---',
    '_Generated by OnePersonAI Tech Agent (Fallback Mode)_',
  ];

  return {
    success: true,
    raw: lines.filter(Boolean).join('\n'),
    usedFallback: true,
  };
}
